# This is a basic workflow to help you get started with Actions

name: Algolia crawler for prod

on:
  # schedule:
  #  - cron: "0 */2 * * *"
  # workflow_dispatch:
    #  inputs:
    #   environment:
    #     description: 'Environment you want to run'
    #     required: true
    #     default: 'https://www.lambdatest.com'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 'Create env file'
        run: |
          touch .env
          echo "APPLICATION_ID=${{ secrets.APPLICATION_ID }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      # Runs a set of commands using the runners shell
      - name: Run algolia crawler on prod website
        run: |
             cat algolia_config.json
             docker run -i --env-file=.env -e "CONFIG=$(cat algolia_config.json | jq -r tostring)" algolia/docsearch-scraper
